LOCAL_DIR := $(GET_LOCAL_DIR)

TARGET := wisky8176_tb_n

MODULES += app/mt_boot \
           dev/lcm

MTK_SECURITY_SW_SUPPORT = yes
MTK_SEC_FASTBOOT_UNLOCK_SUPPORT = yes
MTK_EMMC_SUPPORT = yes
DEFINES += MTK_NEW_COMBO_EMMC_SUPPORT
MTK_KERNEL_POWER_OFF_CHARGING = yes
MTK_LCM_PHYSICAL_ROTATION = 180
CUSTOM_LK_LCM="lq101r1sx01a_wqxga_dsi_vdo"
#hx8392a_dsi_cmd = yes

#FASTBOOT_USE_G_ORIGINAL_PROTOCOL = yes
MTK_VERIFIED_BOOT_SUPPORT = yes

DEBUG := 0
BOOT_LOGO = hd720

#DEFINES += WITH_DEBUG_DCC=1
DEFINES += WITH_DEBUG_UART=1
#DEFINES += WITH_DEBUG_FBCON=1
#DEFINES += MACH_FPGA=y
DEFINES += MTK_VERIFIED_BOOT_SUPPORT

MTK_IN_HOUSE_TEE_SUPPORT=yes
MTK_SEC_VIDEO_PATH_SUPPORT=yes
MTK_WVDRM_L1_SUPPORT = no
PRJ_SHARED_SECURE_POOL_SIZE:=0xe400000

