/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT8173. Copyright MediaTek Inc. (C) 2013.
 * Thu May 18 11:02:07 2017
 * Do Not Modify the File.
 */

#ifndef __CUST_EINT_EXTH
#define __CUST_EINT_EXTH
#ifdef __cplusplus
extern "C" {
#endif
#define CUST_EINT_POLARITY_LOW              0
#define CUST_EINT_POLARITY_HIGH             1
#define CUST_EINT_DEBOUNCE_DISABLE          0
#define CUST_EINT_DEBOUNCE_ENABLE           1
#define CUST_EINT_EDGE_SENSITIVE            0
#define CUST_EINT_LEVEL_SENSITIVE           1
//////////////////////////////////////////////////////////////////////////////




//////////////////////////////////////////////////////////////////////////////
#ifdef __cplusplus
}
#endif
#endif //_CUST_EINT__EXT_H


