/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT8173. Copyright MediaTek Inc. (C) 2013.
 * Thu May 18 11:02:07 2017
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


